### ISSUE TITLE
Sharing is broken

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-files#270]
When I send an email I have a mail not sent message.

And the stacktrace is:

```
[Tue, 28 Apr 2015 11:58:29 GMT] - GET /folders/da326b740bd71d0ff90abb7578382959 - 200 - 44.502 ms -  423

/usr/local/cozy/apps/files/build/server/controllers/sharing.js:28
      return callback(null, mailTemplate(options));
                            ^
TypeError: string is not a function
    at /usr/local/cozy/apps/files/build/server/controllers/sharing.js:28:29
    at /usr/local/cozy/apps/files/build/server/models/user.js:19:14
    at /usr/local/cozy/apps/files/node_modules/cozydb/lib/model.js:240:16
    at /usr/local/cozy/apps/files/node_modules/cozydb/lib/model.js:200:18
    at /usr/local/cozy/apps/files/node_modules/cozydb/lib/cozymodel.js:254:18
    at parseBody (/usr/local/cozy/apps/files/node_modules/cozydb/node_modules/request-json-light/main.js:74:10)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/files/node_modules/cozydb/node_modules/request-json-light/main.js:99:14)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)


```

**Comment by clochix** [comment]
Seems to work now, @frankrousseau can you test ?

**Comment by frankrousseau** [comment]
It looks good. Thank you!
