### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-files#314]
Seen in the logs of an user instance:
```
/usr/local/cozy/apps/files/build/server/controllers/folders.js:469
          content = folders.concat(files);
                            ^
TypeError: Cannot call method 'concat' of undefined
    at /usr/local/cozy/apps/files/build/server/controllers/folders.js:469:29
    at /usr/local/cozy/apps/files/node_modules/async/lib/async.js:254:17
    at done (/usr/local/cozy/apps/files/node_modules/async/lib/async.js:135:19)
    at /usr/local/cozy/apps/files/node_modules/async/lib/async.js:32:16
    at /usr/local/cozy/apps/files/node_modules/async/lib/async.js:251:21
    at /usr/local/cozy/apps/files/node_modules/async/lib/async.js:575:34
    at /usr/local/cozy/apps/files/build/server/controllers/folders.js:444:22
    at /usr/local/cozy/apps/files/node_modules/cozydb/lib/model.js:198:20
    at /usr/local/cozy/apps/files/node_modules/cozydb/lib/cozymodel.js:252:18
    at parseBody (/usr/local/cozy/apps/files/node_modules/cozydb/node_modules/request-json-light/main.js:74:10)
```

I'm unable to reproduce nor understand how `folders` could possibly be null, so I'll add some defensive code, just in case of…

**Comment by frankrousseau** [comment]
+1

**Comment by aenario** [comment]
It's because we dont handle the error case in the async.parallel.
