### ISSUE TITLE
Zip archive of a folder is corrupted

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-files#422]
When trying to download an archive of a huge directory, the user get a corrupted zip file (download stop around 140-150 Mo). Here's the error message inside the logs:
```
TypeError: Cannot read property 'on' of undefined
    at drainStream (/usr/local/cozy/apps/files/node_modules/cozydb/lib/utils/later_stream.js:13:11)
    at LaterStream.module.exports.LaterStream.onReadableReady (/usr/local/cozy/apps/files/node_modules/cozydb/lib/utils/later_stream.js:68:9)
    at /usr/local/cozy/apps/files/node_modules/cozydb/lib/utils/later_stream.js:4:61
    at ClientRequest.<anonymous> (/usr/local/cozy/apps/files/node_modules/cozydb/node_modules/request-json-light/main.js:405:14)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:256:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1255:8)
```

**Comment by clochix** [comment]
don't know if its related, but some users reported that when downloading an archive of huge album in Photos, some pictures inside the archive where corrupted. I was unable to reproduce
