### ISSUE TITLE
Upload stuck at 100%

### ISSUE THREAD

**Issue by Phyks** [cozy/cozy-files#466]
Hi,

I have an upload stuck at 100%, never finishing. See screenshot:
<img width="1677" alt="capture d ecran 2016-09-20 a 10 45 32" src="https://cloud.githubusercontent.com/assets/3856586/18675142/735ef5ac-7f1f-11e6-87d4-7a7119a924c2.png">

The only way to end it is to refresh the page, and the uploaded file is not there. Uploading other files in this folder work.

I think it might be specific to this file. I cannot attach it to this issue, in case you need it for debugging (it is an apk of cozy app), but it is available at https://ufile.io/8d849.

Thanks

**Comment by clochix** [comment]
Well, I tried and uploaded this file into my server without any problem.
Could you have a look at the logs of file app on server side ? `/usr/local/var/log/cozy/files*`

**Comment by Phyks** [comment]
Sorry, I forgot about the logs. Here is what I have there

```
[Tue, 20 Sep 2016 14:45:22 GMT] - POST /files/ - - - - ms -  -
error - files | Error: unrecognized content-type: application/json
    at Form.parse (/usr/local/cozy/apps/files/node_modules/multiparty/index.js:152:21)
    at module.exports.create (/usr/local/cozy/apps/files/build/server/controllers/files.js:330:15)
    at Layer.handle [as handle_request] (/usr/local/cozy/apps/files/node_modules/americano/node_modules/express/lib/router/layer.js:82:5)
    at next (/usr/local/cozy/apps/files/node_modules/americano/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/usr/local/cozy/apps/files/node_modules/americano/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/usr/local/cozy/apps/files/node_modules/americano/node_modules/express/lib/router/layer.js:82:5)
    at /usr/local/cozy/apps/files/node_modules/americano/node_modules/express/lib/router/index.js:267:22
    at Function.proto.process_params (/usr/local/cozy/apps/files/node_modules/americano/node_modules/express/lib/router/index.js:321:12)
    at next (/usr/local/cozy/apps/files/node_modules/americano/node_modules/express/lib/router/index.js:261:10)
    at logger (/usr/local/cozy/apps/files/node_modules/americano/node_modules/morgan/index.js:108:5)
error - files | Error: unrecognized content-type: application/json
    at Form.parse (/usr/local/cozy/apps/files/node_modules/multiparty/index.js:152:21)
    at module.exports.create (/usr/local/cozy/apps/files/build/server/controllers/files.js:330:15)
    at Layer.handle [as handle_request] (/usr/local/cozy/apps/files/node_modules/americano/node_modules/express/lib/router/layer.js:82:5)
    at next (/usr/local/cozy/apps/files/node_modules/americano/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/usr/local/cozy/apps/files/node_modules/americano/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/usr/local/cozy/apps/files/node_modules/americano/node_modules/express/lib/router/layer.js:82:5)
    at /usr/local/cozy/apps/files/node_modules/americano/node_modules/express/lib/router/index.js:267:22
    at Function.proto.process_params (/usr/local/cozy/apps/files/node_modules/americano/node_modules/express/lib/router/index.js:321:12)
    at next (/usr/local/cozy/apps/files/node_modules/americano/node_modules/express/lib/router/index.js:261:10)
    at logger (/usr/local/cozy/apps/files/node_modules/americano/node_modules/morgan/index.js:108:5)

[...]

error - file-model | Cannot destroy binary linked to document XXXXXXXXXXXXX
```

**Comment by nicofrand** [comment]
Same error with a different file for me. I got an error with Firefox but when trying with Chrome, the progress just keeps stuck at 100% like in the screenshot above.

**Comment by clochix** [comment]
For the record, the Files application is being [fully rewritten](https://github.com/cozy/cozy-files-v3). We hope this issue will be gone in next version.
